### ISSUE TITLE
Data availability

### ISSUE THREAD

**Issue by slowkow** [vijaybioinfo/COVID19_2020#1]
I am reading this paper:

https://www.cell.com/cell/fulltext/S0092-8674(20)31307-6

> Data and software availability
> Additional Supplemental Items are available from Mendeley Data at http://dx.doi.org/10.17632/f72dhp8y6h.1. Scripts are available in our repository on GitHub (https://github.com/vijaybioinfo/COVID19_2020). Sequencing data for this study has been deposited onto the Gene Expression Omnibus with the accession no. GSE152522

I'd be interested to have a look at the data deposited at GEO, but here's what I see:

https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE152522

![Screen Shot 2020-10-06 at 3 53 56 PM](https://user-images.githubusercontent.com/209714/95253322-3b176f80-07ec-11eb-8d6f-8aef8889e6f6.png)

Could I please ask if you might be able to go ahead and make the accession public?

Thank you!

**Comment by vijaybioinfo** [comment]
Dear @slowkow,

The data is available now.

Let me know if you need anything else,
Ciro
