### ISSUE TITLE
.rds file avaiability

### ISSUE THREAD

**Issue by dm8000** [vijaybioinfo/COVID19_2020#3]
Hello
do you plan to make the Seurat object available?

**Comment by quan6688** [comment]
I have the same question. Becuase I want to follow you R script to learn the analysis of single cell.

**Comment by vijaybioinfo** [comment]
Hi,

Thank you for your interest. I just added the [link](https://drive.google.com/drive/folders/1aMo8RgZt9bZy5tc94Kr1x-wuzUoRbOCz?usp=sharing) to the Seurat object.

Let me know if you have any questions.
Ciro

**Comment by quan6688** [comment]
Thank you for your speedy reply.  I have downloaded the CD4T3_ seraut.rdata,  and intend to careful study this script for my data anlysis.  If i have many quesetion about data analysis, may i can send message to you  for help?
