### ISSUE TITLE
Dataset availability

### ISSUE THREAD

**Issue by chisangad** [vijaybioinfo/COVID19_2020#4]
Hi 

I was just going through your recent paper in Science Immunology ; https://immunology.sciencemag.org/content/6/55/eabe4782 and I was looking to use the data that is provided for in the link in the paper below.
https://drive.google.com/drive/folders/1aMo8RgZt9bZy5tc94Kr1x-wuzUoRbOCz 

I wanted to generate a couple of UMAP plots using the metadata included in the R data object but couldn’t replicate Figure 2A, so I had a look at the shared code and I realised I might not have been using the correct data; 
`clustname = “/home/ciro/large/covid19/results/clustering/CD8T24_R1n2n3_sng_20p/clustering/zetInfo/clustCells25PCs_30Ks_0.06667JD.RData"
nres = 'RNA_snn_res.0.2'

mycells <- theObjectSavedIn(clustname)

mycells@meta.data$Cluster <- factormix(mycells@meta.data[, nres])
p <- DimPlot(
  object = mycells,
  reduction = 'umap',
  group.by = "Cluster",
  label = TRUE
)
`

Do you mind sharing the R Data object file (“clustCells25PCs_30Ks_0.06667JD.RData”) used in the script above or if you don’t mind you can explain how you came up with the ‘RNA_snn_res.0.2’ column.

Thanks,
David

**Comment by VicenteFR** [comment]
Hi @chisangad,

Thanks for your interest in these data!
You can now find the data stored as a seurat object (compressed in RDS format) in this [link](https://drive.google.com/drive/folders/1aMo8RgZt9bZy5tc94Kr1x-wuzUoRbOCz?usp=sharing). Given the format of the file, you should be able to import the data into your R session using:

`seurat.obj <- readRDS(file='/path/to/the/seurat/object/SeuratObject_CD8TCells_24hData.RDS')`

For what it's worth, we obtained the clusters identified by column 'RNA_snn_res.0.2' through Seurat's functions [FindNeighbors](https://www.rdocumentation.org/packages/Seurat/versions/3.0.1/topics/FindNeighbors) and [FindClusters](https://www.rdocumentation.org/packages/Seurat/versions/1.4.0/topics/FindClusters) using a value of 0.2 for the argument resolution. Please see the methods section of the manuscript for further details and feel free to ask any other specific questions.

Thanks,
Vicente

**Comment by chisangad** [comment]
Thank you very much @VicenteFR
